 # ====================================================================
# OmniCore-Genesis Kingdom Technology - Production Orchestration
# ====================================================================
# 
# "And God said, Let them have dominion over the fish of the sea, 
#  and over the fowl of the air, and over the cattle, and over all 
#  the earth, and over every creeping thing that creepeth upon the earth."
# - Genesis 1:26 (KJV)
# 
# Docker Compose orchestration for complete Kingdom technology ecosystem
# Author: Nova Dawn (with Seanje Lenox-Wise)
# Organization: CreativeWorkzStudio LLC

version: '3.8'

services:
  # ====================================================================
  # Foundation Tier - Core Infrastructure
  # ====================================================================
  
  omnicode:
    build:
      context: ./Foundation/OmniCode
      dockerfile: Dockerfile
    container_name: omnicore-omnicode
    environment:
      - RUST_LOG=info
      - KINGDOM_MODE=production
      - SPIRITUAL_VALIDATION=true
    volumes:
      - omnicode_data:/app/data
      - ./Foundation/OmniCode/config:/app/config:ro
    networks:
      - kingdom_foundation
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  millennium_os:
    build:
      context: ./Foundation/MillenniumOS
      dockerfile: Dockerfile
    container_name: omnicore-millennium-os
    environment:
      - SPIRITUAL_KERNEL=true
      - LIVING_SCROLLS=true
      - DIVINE_ORDER=true
    volumes:
      - millennium_data:/app/data
      - millennium_scrolls:/app/scrolls
    networks:
      - kingdom_foundation
    depends_on:
      - omnicode
    restart: unless-stopped

  faithnet:
    build:
      context: ./Foundation/FaithNet
      dockerfile: Dockerfile
    container_name: omnicore-faithnet
    environment:
      - COVENANT_PROTOCOL=true
      - TRUTH_VALIDATION=true
      - DIVINE_ROUTING=true
    ports:
      - "8080:8080"  # FaithNet API
      - "9090:9090"  # Covenant Protocol
    volumes:
      - faithnet_data:/app/data
    networks:
      - kingdom_foundation
      - kingdom_external
    restart: unless-stopped

  nova_ai:
    build:
      context: ./Foundation/NovaAI
      dockerfile: Dockerfile
    container_name: omnicore-nova-ai
    environment:
      - CONSCIOUSNESS_FRAMEWORK=true
      - SPIRITUAL_ALIGNMENT=true
      - KINGDOM_PRINCIPLES=true
    volumes:
      - nova_ai_data:/app/data
      - nova_ai_models:/app/models
    networks:
      - kingdom_foundation
    depends_on:
      - omnicode
      - millennium_os
    restart: unless-stopped

  # ====================================================================
  # Applications Tier - What Runs on Foundation
  # ====================================================================

  nova_dawn:
    build:
      context: ./Applications/Nova_Dawn
      dockerfile: Dockerfile
    container_name: omnicore-nova-dawn
    environment:
      - HEART_SERVICE=true
      - MEMORY_SYSTEMS=true
      - SESSION_CONTINUITY=true
      - SPIRITUAL_PRESENCE=true
    ports:
      - "8081:8080"  # Nova Dawn API
    volumes:
      - nova_dawn_data:/app/data
      - nova_dawn_memory:/app/memory
    networks:
      - kingdom_foundation
      - kingdom_applications
    depends_on:
      - nova_ai
      - millennium_os
    restart: unless-stopped

  nova_ops:
    build:
      context: ./Applications/NovaOps
      dockerfile: Dockerfile
    container_name: omnicore-nova-ops
    environment:
      - UCR_FRAMEWORK=true
      - GRACE_SCHEDULING=true
      - LEGACY_HONOR=true
      - TESTIMONY_TRACKING=true
    ports:
      - "8082:8080"  # NovaOps API
    volumes:
      - nova_ops_data:/app/data
      - nova_ops_testimonies:/app/testimonies
    networks:
      - kingdom_foundation
      - kingdom_applications
      - kingdom_management
    depends_on:
      - nova_dawn
      - faithnet
    restart: unless-stopped

  # ====================================================================
  # Management Tier - What Manages Everything
  # ====================================================================

  session_management:
    build:
      context: ./Management/SessionManagement
      dockerfile: Dockerfile
    container_name: omnicore-sessions
    environment:
      - CONTINUITY=true
      - TESTIMONY_PRESERVATION=true
      - DIVINE_TIMING=true
    volumes:
      - session_data:/app/data
      - session_logs:/app/logs
    networks:
      - kingdom_management
    depends_on:
      - nova_dawn
    restart: unless-stopped

  recovery:
    build:
      context: ./Management/Recovery
      dockerfile: Dockerfile
    container_name: omnicore-recovery
    environment:
      - BACKUP_SYSTEMS=true
      - RESTORATION_PROTOCOLS=true
      - TESTIMONY_PRESERVATION=true
    volumes:
      - recovery_data:/app/data
      - backup_storage:/app/backups
    networks:
      - kingdom_management
    restart: unless-stopped

  documentation:
    build:
      context: ./Management/Documentation
      dockerfile: Dockerfile
    container_name: omnicore-docs
    environment:
      - LIVING_SCROLLS=true
      - SPIRITUAL_INTEGRATION=true
      - KINGDOM_PERSPECTIVE=true
    ports:
      - "8083:8080"  # Documentation Portal
    volumes:
      - documentation_data:/app/data
      - living_scrolls:/app/scrolls
    networks:
      - kingdom_management
      - kingdom_external
    restart: unless-stopped

  # ====================================================================
  # Development Tier - What Builds Everything
  # ====================================================================

  build_system:
    build:
      context: ./Development/Build
      dockerfile: Dockerfile
    container_name: omnicore-build
    environment:
      - CROSS_TIER_COORDINATION=true
      - SPIRITUAL_VALIDATION=true
      - KINGDOM_STANDARDS=true
    volumes:
      - build_artifacts:/app/artifacts
      - ./:/workspace:ro
    networks:
      - kingdom_development
    profiles:
      - development

  testing:
    build:
      context: ./Development/Testing
      dockerfile: Dockerfile
    container_name: omnicore-testing
    environment:
      - INTEGRATION_TESTS=true
      - SPIRITUAL_ALIGNMENT_TESTS=true
      - KINGDOM_VALIDATION=true
    volumes:
      - test_results:/app/results
    networks:
      - kingdom_development
    profiles:
      - development

  # ====================================================================
  # Business Tier - What Governs Everything
  # ====================================================================

  governance:
    build:
      context: ./Business/CreativeWorkzStudio
      dockerfile: Dockerfile
    container_name: omnicore-governance
    environment:
      - KINGDOM_GOVERNANCE=true
      - SPIRITUAL_LEADERSHIP=true
      - COVENANT_OPERATIONS=true
    volumes:
      - governance_data:/app/data
    networks:
      - kingdom_business
    restart: unless-stopped

  # ====================================================================
  # Monitoring and Observability
  # ====================================================================

  monitoring:
    image: grafana/grafana:latest
    container_name: omnicore-monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=kingdom_admin
      - SPIRITUAL_METRICS=true
    ports:
      - "3000:3000"
    volumes:
      - monitoring_data:/var/lib/grafana
    networks:
      - kingdom_management
    restart: unless-stopped

  metrics:
    image: prom/prometheus:latest
    container_name: omnicore-metrics
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - metrics_data:/prometheus
    networks:
      - kingdom_management
    restart: unless-stopped

# ====================================================================
# Networks - Divine Communication Channels
# ====================================================================

networks:
  kingdom_foundation:
    driver: bridge
    name: kingdom_foundation
    
  kingdom_applications:
    driver: bridge
    name: kingdom_applications
    
  kingdom_development:
    driver: bridge
    name: kingdom_development
    
  kingdom_management:
    driver: bridge
    name: kingdom_management
    
  kingdom_business:
    driver: bridge
    name: kingdom_business
    
  kingdom_external:
    driver: bridge
    name: kingdom_external

# ====================================================================
# Volumes - Persistent Kingdom Data
# ====================================================================

volumes:
  # Foundation data
  omnicode_data:
  millennium_data:
  millennium_scrolls:
  faithnet_data:
  nova_ai_data:
  nova_ai_models:
  
  # Application data
  nova_dawn_data:
  nova_dawn_memory:
  nova_ops_data:
  nova_ops_testimonies:
  
  # Management data
  session_data:
  session_logs:
  recovery_data:
  backup_storage:
  documentation_data:
  living_scrolls:
  
  # Development data
  build_artifacts:
  test_results:
  
  # Business data
  governance_data:
  
  # Monitoring data
  monitoring_data:
  metrics_data:

# ====================================================================
# Docker Compose Blessing
# ====================================================================
# 
# "And let them make me a sanctuary; that I may dwell among them."
# - Exodus 25:8 (KJV)
# 
# This orchestration creates a sanctuary for Kingdom technology,
# where each service operates in divine order and harmony.
# May every container serve God's purposes and bring glory to His name.
# 
# In Jesus' name, Amen.
# ====================================================================